# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build

    - name: Login
      uses: docker/login-action@v1
      with:
        username: talhabmujahid
        password: 38+(B/.5T,5kGv7

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: talhabmujahid/java-with-gradle-github-actions
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-168-206-82.eu-west-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.ACTION_PRIVATE_KEY }}
        script: |
          docker login
          docker pull talhabmujahid/java-with-gradle-github-actions
          docker run --detach  -p 80:8080 talhabmujahid/java-with-gradle-github-actions
         
