# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build

    - name: Login
      uses: docker/login-action@v1
      with:
        username: talhabmujahid
        password: 38+(B/.5T,5kGv7

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: talhabmujahid/java-with-gradle-github-actions
        addLatest: true
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ec2-18-168-206-82.eu-west-2.compute.amazonaws.com
        username: ec2-user
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAnPDOt3zNRR/wsST9hvqI8YIN7X8ub90xnyazqePkFWL/6tp9
          2QB8BhlCGp2BYELzdM0w/kQbki8P7/5YvpLUk+gG1pLonhsLhogKJS8DZbtMxAeC
          7mWd55PDXehrNLs1XFnnRWy6pwG5sEe5iMWY1hgW4uA29DuSGAW+tTgjkwUnA3cj
          Yhg7kaiYkBLLZCS4CC9Cj55SeC+cJro8W1zPmpUBhkGiPoOPB1DG5k8sYjO3kGDM
          ZbBRrj9q0M1IOHVwUspw4xnUM0PBVKUr10aRxjtz9R+vbbZQulczrzOGxXdegYBq
          Uv7t3kSdVCKzAHqqFaR7pKq3T/AlCWwDI2V2iwIDAQABAoIBABpR7GkrXgWcwLIE
          wRwVAkh2hj1xWela0Eqfo/v3AzZu/vp1ICv3f9VKASMTjTIGqGvLSc8qvvD6QZL/
          NgTn/Qy9GgB8bNSvNnSedg0cYFZ8Xfh2RggTNLM0vcwPAYO7bcyKK1YiUP9XM7wT
          m1MLyIEHUzdDYRP+tZafyAb+XkD2lbdua82dTUBuzToAndBlcYyLbcNj9mjH38Jd
          LLx1pH1Hxzedv0US+FY3lTyR3y60CDVMvH9TAZ6jgt6BcEJt1iBma1gsIcY42841
          AwF9sn/DtYUEEGA6R1vEijj5NHWmL016cElWpmh4UjZHt1/7FIaIDcS3+chKo1z4
          C/MJApkCgYEA3ETNXxdnVgBo0qgJ5qwiCqwj+iLSrxkjjpPyIJOruoP7R16TZbTs
          XcSiWKE9lDUs5pgjz6KcYyzBsYCgctaLzk0HfhMYzL34SL4WJp+jZDniJ7x3kxMZ
          R0BoRzEQBWc3gFq+YaKdRGAapkh55pCpuh3nRrNwyfdI8dxv1b+QT+cCgYEAtmYm
          ssx+YUa200fKeckxnIUVr+oii2MABZoewGo2ha68d4gEKZr75YLgGf8e+D24ynaq
          1gy2+beqLRKtesHZaKwxH+RBvCXJA1vqCiqxsF4QLZ9QMszqDJ6exuk/ZhjNOgub
          EoABhP3nAjA0snNAs+44+Oy2sIZ1USNbI8q2n70CgYBsO9aacjqRtNPNJ0ruMQjt
          K5bmE3RpG7YwGhxwy38nwDCZ6iwNXvCCRtvrJxfGGrb8fCekoGeuB9EJcoXkx+2c
          qpcS6TlXacV1oQnrYqf72MF6+w3alBjovQpAaShRL13DUVOZUDls3rhZmuVjWRQ9
          YvJA+G1koIEUb1f4tQ+pYwKBgQCxxraJJo83OLkRDLPoJ5TXPU95+fZZbNCkpSa7
          28nwWfMPfd6wvoItnHXYYLRKt73Yd/jiT9o3Yi/XZpD3SOEiCFKJBuya+SkGwRtH
          dX1irQuPq+t62AZ27lNLBCPq2tmMbatjSKgye1Yg5+M02uiBdvrIg888FpFZ1+AI
          7pc48QKBgQCs9sCHDJjU+GlAFPz2huK/00Goqz9G41x/L/+vneWob6iKNIVvGWkf
          cdpXE+dNG1w38cabAa1SRj4Rv9geOjz0IENgiW46a3Cxziw1vq7DCOnx1za1w4ZG
          gbftBn0BtmHjW4hiJ3yKV6SoVMjitNS8Mkop6fac+qOpHfH9R9QnJw==
          -----END RSA PRIVATE KEY-----
        script: |
          docker login -u talhabmujahid -p '38+(B/.5T,5kGv7'
          docker pull talhabmujahid/java-with-gradle-github-actions
          docker run --detach  -p 80:8080 talhabmujahid/java-with-gradle-github-actions
         
